### ISSUE TITLE
Exception: -setDelegate: only defined for abstract class. Define -[PKMultipartBodyStream setDelegate:]!'

### ISSUE THREAD

**Issue by ayoy** [pyke369/PKMultipartInputStream#10]
Hi and thanks a lot for this nice and handy class!

I came across a small issue when using PKMultipartInputStream with NSURLSession and NSURLSessionUploadTask. The exception as in title is thrown, and it's basically the same as described in [this AFNetworking issue](https://github.com/AFNetworking/AFNetworking/issues/2201). The solution requires synthesizing a delegate property in PKMultipartBodyStream.m, just like Mattt did in AFMultipartBodyStream [in this commit](https://github.com/AFNetworking/AFNetworking/commit/ca1441e09831bb9c9cece069a6330555642e49df).

For now, as a workaround, I subclass PKMultipartBodyStream and synthesize a delegate in my class. It would be nice to have this fixed upstream, though :)

**Comment by pyke369** [comment]
Hello ayoy,

Would you be kind enough to propose a PR for this?

Thanks a lot.
Pierre-Yves

**Comment by ayoy** [comment]
Sure, here you are :)

**Comment by pyke369** [comment]
Merged. Thx.
