### ISSUE TITLE
Publish 1.2.0 on Cocoapods

### ISSUE THREAD

**Issue by FGoessler** [pyke369/PKMultipartInputStream#13]
Hi,

could you please publish the latest version of the podspec on the official CocoaPods Repo?

Otherwise it's not possible to reference this project without using the explicit git path.

Official documentation:
https://guides.cocoapods.org/making/specs-and-specs-repo.html
https://guides.cocoapods.org/making/getting-setup-with-trunk.html

Thanks!

**Comment by pyke369** [comment]
Hello,

Podspec updated (to version 1.3.0), but unfortunately I cannot push to Cocoapods b/c this pod is actually owned by https://cocoapods.org/owners/889 (Ernesto Rivera), who was kind enough to publish this library at Cocoapods in the first place. I'll try to take ownership back and update soon.

Pierre-Yves.

**Comment by pyke369** [comment]
Ok, done.
