### ISSUE TITLE
Crash. Define -[PKMultipartInputStream propertyForKey:]!'`

### ISSUE THREAD

**Issue by banshchikov** [pyke369/PKMultipartInputStream#14]
Hi there! I'm trying to use ShareKit SDK to upload video to OneNote. It crashes everytime:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -propertyForKey: only defined for abstract class.  Define -[PKMultipartInputStream propertyForKey:]!'`

**Comment by banshchikov** [comment]
Fixed. I've added few methods to implementation:

```
- (id)propertyForKey:(NSStreamPropertyKey)key {
    return nil;
}

- (BOOL)setProperty:(id)property forKey:(NSStreamPropertyKey)key {
    return NO;
}
```

**Comment by pyke369** [comment]
Hi Andrey,

Could you submit a PR with this changes, I will happily merge it.

Thanks,
Pierre-Yves
