### ISSUE TITLE
removeFromRunLoop:forMode: crash in iOS 8

### ISSUE THREAD

**Issue by paul-lalonde** [pyke369/PKMultipartInputStream#6]
Trapping the exception (deep in new SPDY handling, it seems), I'm getting:
(NSException *) $0 = 0x000000017104e430 name:@"NSInvalidArgumentException" reason:@"*** -removeFromRunLoop:forMode: only defined for abstract class.  Define -[PKMultipartInputStream removeFromRunLoop:forMode:]!"

Any clues?

**Comment by VilemKurz** [comment]
This is fixed now, can be closed.
