### ISSUE TITLE
Upload array of images 

### ISSUE THREAD

**Issue by nadagamal** [pyke369/PKMultipartInputStream#7]
Hi , 
Thanks a lot for your good library . I want to upload multiple  images to server . What can I do .
Appreciate you answer.
Regards,
Nada Gamal

**Comment by pyke369** [comment]
Hello nadagamal,

You could probably add multiple "file" parts, i.e. for instance use the:
```
(void)addPartWithName:(NSString *)name filename:(NSString *)filename path:(NSString *)path;
```
multiple times.

Regards,
Pierre-Yves
