### ISSUE TITLE
update podspec

### ISSUE THREAD

**Issue by VilemKurz** [pyke369/PKMultipartInputStream#9]
Please, add a new tag and update podspec accordingly. This is desperately needed, because the latest commit fixes crash on iOS8.

**Comment by pyke369** [comment]
Done.

**Comment by VilemKurz** [comment]
Thank you. Also, please push the pod spec to [cocoapods trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk.html), so that it is easily accessible via cocoapods.
